"""tools/make_rebuttal_report.py — assemble the rebuttal deliverables into one
markdown report from the raw CSVs (read-only; no experiment re-run).

Covers:
  1. Overhead (theoretical FLOPs/BW)   -> results/overhead_analysis/
  2. Long-context PG-19 PPL + WT-2      -> results/longctx_ppl/
  3. Query-aware routing vs SL          -> results/longctx_ppl/scaling/
  4. Downstream MMLU / ARC-Challenge    -> results/downstream_mc/

Usage: python tools/make_rebuttal_report.py
"""
from __future__ import annotations
import csv, glob, os

ROOT = "results"
OUT = os.path.join(ROOT, "REBUTTAL_RESULTS.md")


def rd(p):
    return list(csv.DictReader(open(p))) if os.path.exists(p) and os.path.getsize(p) else []


def rdglob(pat):
    rows = []
    for p in glob.glob(pat):
        rows += rd(p)
    return rows


def fnum(x):
    try:
        return float(x)
    except Exception:
        return None


def sec(title):
    return f"\n## {title}\n"


def main():
    L = ["# CARE-KV — rebuttal experiment results (auto-assembled)\n",
         "> Generated by tools/make_rebuttal_report.py from raw CSVs. "
         "CARE-KV rows are only counted when K_reads+V_reads>0 (router fired).\n"]

    # ── 1. Overhead ──
    L.append(sec("1. Decode-step overhead — theoretical FLOPs / memory bandwidth"))
    ov = rd("results/overhead_analysis/overhead_flops_bw.csv")
    if ov:
        cols = ["model", "context", "flop_overhead_vs_base_pct",
                "bw_overhead_vs_base_pct", "bw_carekv_vs_fp16_ratio",
                "kv_carekv_vs_fp16_ratio"]
        L.append("| " + " | ".join(cols) + " |")
        L.append("|" + "---|" * len(cols))
        for r in ov:
            L.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
        L.append("\n_CARE-KV adds a small algorithmic overhead over plain INT3 "
                 "(single-digit % FLOPs, <=10% read-BW) and still reads far less "
                 "than fp16. See results/overhead_analysis/OVERHEAD_ANALYSIS.md._")
    pb = rd("results/overhead_analysis/prototype_runtime_breakdown_sl256.csv")
    if pb:
        L.append("\n**Prototype wall-clock breakdown (why measured latency != algorithmic "
                 "cost):**\n")
        L.append("| stage | total_s | % of forward | ms/call |")
        L.append("|---|---|---|---|")
        for r in pb:
            if r.get("pct_of_forward") not in ("", None):
                L.append(f"| {r['stage']} | {r['total_s']} | {r['pct_of_forward']} | {r['ms_per_call']} |")
        L.append("\n_The per-(head,t) Python-loop correction dominates the prototype "
                 "wall-clock — an implementation artifact, not the FLOPs above._")

    # ── 2. Long-context PG-19 + WT-2 PPL ──
    L.append(sec("2. Long-context PPL — PG-19 (SL up to 8192) + WikiText-2 continuity"))
    lc = (rdglob("results/longctx_ppl/*.csv") +
          rdglob("results/longctx_ppl/scaling/*.csv"))
    # index best (real) per (dataset, sl, mode)
    idx = {}
    for r in lc:
        if r.get("status") != "real":
            continue
        idx[(r["dataset"], int(r["seq_len"]), r["mode"])] = r
    for dsname in ["pg19", "wikitext"]:
        sls = sorted({sl for (d, sl, _) in idx if d == dsname})
        if not sls:
            continue
        L.append(f"\n### {dsname}\n")
        modes = ["fp16", "base_quant_int3", "turboquant_int3", "carekv_qaware",
                 "carekv_stored_int3"]
        present = [m for m in modes if any((dsname, sl, m) in idx for sl in sls)]
        L.append("| SL | " + " | ".join(present) + " | N | K/V reads (carekv) |")
        L.append("|" + "---|" * (len(present) + 3))
        for sl in sls:
            cells = []
            n = kv = "-"
            for m in present:
                r = idx.get((dsname, sl, m))
                cells.append(f"{r['ppl']}" if r else "-")
                if r and "carekv" in m:
                    n = r["num_samples"]; kv = f"{r['k_reads']}/{r['v_reads']}"
            L.append(f"| {sl} | " + " | ".join(cells) + f" | {n} | {kv} |")
        if dsname == "pg19":
            L.append("\n_**These PPLs are N=2-window EXPLORATORY, not rigorous** "
                     "(2 windows is too noisy to rank close methods). CARE-KV "
                     "correction is O(T·S·D) per prefill position in the current "
                     "prototype (~30 min/window at SL2048, ~2 h/window at SL4096), so "
                     "CARE-KV PPL is reported up to SL2048; SL4096/8192 is "
                     "prototype-runtime-bound (see §1)._")
            L.append("\n_**vs baselines (ground truth — do not overstate):** CARE-KV "
                     "reliably beats plain **INT3 base** (repo NS=64: 12W/0L). "
                     "**vs TurboQuant it is model-dependent** — CARE-KV wins 3/4 "
                     "models on PPL (TinyLlama/Mistral/SOLAR) but **loses on Yi-6B**, "
                     "and on the rigorous NS=64 WikiText-2 grid TurboQuant is ahead "
                     "(gap tracks K-outlier severity). The N=2 rows above must NOT be "
                     "read as CARE-KV beating TurboQuant — that needs NS~16-64. "
                     "See results/CARE_KV_RESULTS_CONSOLIDATED.md._")

    # ── 3. Query-aware routing vs SL ──
    L.append(sec("3. Query-aware routing advantage vs sequence length"))
    rows = [r for (d, sl, m), r in idx.items() if m in ("carekv_qaware", "carekv_magnitude")]
    if rows:
        L.append("| dataset | SL | qaware PPL | magnitude PPL (q-agnostic) | base PPL | "
                 "Δ(mag−qaware) | Δ(base−qaware) | eff#keys exp(H) | top1% mass |")
        L.append("|" + "---|" * 9)
        keyset = sorted({(d, sl) for (d, sl, m) in idx
                         if m == "carekv_qaware"})
        for (d, sl) in keyset:
            qa = idx.get((d, sl, "carekv_qaware"))
            mg = idx.get((d, sl, "carekv_magnitude"))
            base = idx.get((d, sl, "base_quant_int3"))
            qp = fnum(qa["ppl"]) if qa else None
            mp = fnum(mg["ppl"]) if mg else None
            bp = fnum(base["ppl"]) if base else None
            dm = round(mp - qp, 4) if (mp and qp) else "-"
            db = round(bp - qp, 4) if (bp and qp) else "-"
            ne = fnum(qa.get("imp_norm_entropy")) if qa else None
            effk = round(sl ** ne, 1) if ne else "-"
            L.append(f"| {d} | {sl} | {qa['ppl'] if qa else '-'} | "
                     f"{mg['ppl'] if mg else '-'} | {base['ppl'] if base else '-'} | "
                     f"{dm} | {db} | {effk} | "
                     f"{qa.get('imp_top1pct_mass','-') if qa else '-'} |")
        L.append("\n_See results/longctx_ppl/fig_query_aware_vs_SL.png. Positive and "
                 "growing Δ(mag−qaware) and Δ(base−qaware) = the query-aware utility's "
                 "advantage widens with SL. Mechanism: the effective # of attended keys "
                 "GROWS and the top-1% mass share FALLS with SL — attention importance "
                 "disperses over more tokens — so, under a fixed correction budget, "
                 "picking the right slots (only query-aware routing does) matters more._")

    # ── 4. Downstream MMLU / ARC ──
    L.append(sec("4. Downstream tasks — MMLU (0-shot) + ARC-Challenge"))
    dm = rdglob("results/downstream_mc/*.csv")
    dm = [r for r in dm if not r.get("model_id", "").startswith("TinyLlama")]  # drop smokes
    if dm:
        by = {}
        for r in dm:
            by.setdefault((r["model_id"], r["task"], r["metric"]), {})[r["mode"]] = r
        modes = ["fp16", "base_quant_int3", "turboquant_int3", "carekv_stored_int3"]
        L.append("_Each cell is `acc (n)`; compare only within the same n "
                 "(CARE-KV is n=64 — its runtime ceiling)._\n")
        L.append("| model | task | metric | " + " | ".join(modes) + " | carekv K/V |")
        L.append("|" + "---|" * (len(modes) + 4))
        for (mid, task, metric), d in sorted(by.items()):
            cells = []
            kv = "-"
            for m in modes:
                r = d.get(m)
                cells.append(f"{r['value']} ({r['n']})" if r else "-")
                if r and "carekv" in m:
                    kv = f"{r['k_reads']}/{r['v_reads']}"
            L.append(f"| {mid.split('/')[-1]} | {task} | {metric} | " +
                     " | ".join(cells) + f" | {kv} |")
        L.append("\n_CARE-KV downstream is prototype-runtime-bound "
                 "(~100 s/forward on DeepSeek-7B; router fired, K/V reads shown), so "
                 "n is capped (MMLU n=64, LAMBADA n=100). At n=64, **MMLU** (1.5%/q) "
                 "cannot resolve the three INT3 methods (all 0.406) — read as "
                 "'CARE-KV does not hurt', not a win._")
        L.append("\n_**LAMBADA** (1 forward/example, so it reaches n=100–300 and has "
                 "real resolution) is the informative row and matches the PPL ground "
                 "truth exactly: **CARE-KV 0.79 > INT3 base 0.783** (beats the naive "
                 "baseline) but **TurboQuant 0.807 > CARE-KV** (Turbo ahead on this "
                 "outlier-heavy model), all just below fp16 0.81. So downstream: "
                 "CARE-KV beats plain INT3 and preserves accuracy, but does NOT beat "
                 "TurboQuant — consistent with §2 and results/CARE_KV_RESULTS_"
                 "CONSOLIDATED.md. (CARE-KV n=100 vs fast-mode n=300; cells show n.)_")
    else:
        L.append("_(no downstream rows yet)_")

    # ── 5. Per-layer query-aware benefit ──
    pl = rd("results/longctx_ppl/per_layer_importance.csv")
    if pl:
        L.append(sec("5. Per-layer query-aware benefit (importance dispersion)"))
        L.append("_A layer whose per-key attention mass is more DISPERSED (lower Gini) "
                 "has no dominant key, so which slot to correct depends on the query -> "
                 "query-aware routing helps it most. Per-layer dispersion from a CARE-KV "
                 "forward (see results/longctx_ppl/fig_per_layer_importance.png)._\n")
        rows_pl = [r for r in pl if r.get("gini")]
        disp = sorted(rows_pl, key=lambda r: float(r["gini"]))[:5]
        conc = sorted(rows_pl, key=lambda r: -float(r["gini"]))[:5]
        gv = [float(r["gini"]) for r in rows_pl]
        L.append(f"- layers profiled: **{len(rows_pl)}**, Gini range "
                 f"**{min(gv):.3f}–{max(gv):.3f}** (lower = more dispersed = more "
                 f"query-aware benefit).")
        L.append(f"- **most-dispersed (query-aware helps most):** layers "
                 f"{', '.join(str(r['layer']) for r in disp)}.")
        L.append(f"- **most-concentrated (least benefit):** layers "
                 f"{', '.join(str(r['layer']) for r in conc)}.")

    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"[report] wrote {OUT}")


if __name__ == "__main__":
    main()
